use_frameworks!

platform :ios, '8.0'

target 'ShunLianLib_Example' do
  pod 'ShunLianLib', :path => '../'

  target 'ShunLianLib_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
